algorytm=BF
plik_wejsciowy=dane/matrix_11x11.atsp
plik_wyjsciowy=wyniki/wyniki.csv
liczba_powtorzen=2
rozmiar_poczatkowy=6
rozmiar_koncowy=15
pokazuj_pasek_postepu=1
tryb_z_pliku=1
tryb_symulacji=1
czy_symetryczny=0

#Do symulacji PZ potrzeba 
