algorytm=BF
plik_wejsciowy=dane/matrix_11x11.atsp
plik_wyjsciowy=wyniki/wyniki.csv
liczba_powtorzen=1
rozmiar_poczatkowy=6
rozmiar_koncowy=15
pokazuj_pasek_postepu=1
tryb_z_pliku=0
tryb_symulacji=1
czy_symetryczny=0
generuj_pliki_raz=0
generuj_min_n=6
generuj_max_n=15
katalog_sym=dane/DaneSymulacjaBF/BF_TSP/sym
katalog_asym=dane/DaneSymulacjaBF/BF_ATSP/asym
wyswietl_macierze_symulacji=0

#Do symulacji PZ potrzeba 
